version: "3.8"
services:
  db:
    images: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: books
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
